### ISSUE TITLE
invalid utf8 byte sequence error during makehashes

### ISSUE THREAD

**Issue by rworkman** [poeml/mirrorbrain#170]
This only happens with this one file - if I skip that file using a regex match (-i flag) then the makehash operation completes successfully). I can of course skip this file without much consequence, but I'd like to find out why it's happening and how to prevent it in case other files trigger it later.

The "0" printed at the end of the line is from me uncommenting the "print len(self.zsums)" line in hashes.py

File 'slackware-14.0/source/a/lilo/lilo-23.2.tar.gz' not in database. Not on mirrors yet? Will be inserted.
Hashing '/home/ftp/pub/slackware/slackware-14.0/source/a/lilo/lilo-23.2.tar.gz'... 0
done.
Traceback (most recent call last):
  File "/usr/bin/mb", line 1677, in <module>
    r = mirrordoctor.main()
  File "/usr/lib64/python2.7/site-packages/cmdln.py", line 262, in main
    return self.cmd(args)
  File "/usr/lib64/python2.7/site-packages/cmdln.py", line 285, in cmd
    retval = self.onecmd(argv)
  File "/usr/lib64/python2.7/site-packages/cmdln.py", line 423, in onecmd
    return self._dispatch_cmd(handler, argv)
  File "/usr/lib64/python2.7/site-packages/cmdln.py", line 1124, in _dispatch_cmd
    return handler(argv[0], opts, *args)
  File "/usr/bin/mb", line 1134, in do_makehashes
    force=opts.force)
  File "/usr/lib64/python2.7/site-packages/mb/hashes.py", line 171, in check_db
    binascii.hexlify(''.join(self.hb.zsums))]
psycopg2.DataError: invalid byte sequence for encoding "UTF8": 0x8b

**Comment by rworkman** [comment]
Well, I *think* this is a false alarm due to a corrupted file on the master mirror. That initial "8B" certainly looks suspicious given the error message thrown by mb...

$ pwd
/mirrors/ftp.slackware.com/pub/slackware/slackware-14.0/source/a/lilo
connie $ less lilo-23.2.tar.gz.asc 
"lilo-23.2.tar.gz.asc" may be a binary file.  See it anyway? 
^_<8B>^H^@^@^@^@^@^@^Cmι^N<82>0^@<80><E1><BD>O<D1>Qc^@94j<E2>P<B0>VPESC<E4>R܈T, $^\<8A><<BD><C7><EC>?<FE><D3><9F>tLL
mbC<D7>$^Ty<BE><83><BF>[^@^A<AB>j^^V^KH<8A><D6>&<F0>!<8B><9A>(<8F><E1><80>P_<DA><F1><A2><ED><86>^@p^\b<A4>c^C<A1>p<8D>2%<B9>oKd$<D9><C1><E5><96>^?֥[m6<81><8D>^Lf<B1>8:<CA><F2><AB><CF><F9><F3>$<A5>W/N<AB>~<9A>u`<D3>d<A8><E0>N<A4>&<E6>e<CF>^Rw>RR5<9C><E8>9K<B5><DE>m"<B0>^L<BD><99>^B~"LW<FF><9C>o<F1><87><EB>!<C6>^@^@^@
lilo-23.2.tar.gz.asc lines 1-2/2 (END)

**Comment by rworkman** [comment]
Yep, definitely the culprit.  Closing this bug.
